services:
  customer-db:
    container_name: client-hub-postgres
    image: postgres:15.3
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /data/postgres
    volumes:
      - customer-db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - customer-network
    restart: unless-stopped

  client-hub-api:
    container_name: client-hub-api
    image: mbraga01/client-hub-api
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://customer-db:5432/${POSTGRES_DB}"
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8088:8080"
    networks:
      - customer-network
    depends_on:
      - customer-db
    restart: unless-stopped
#    command:
#      - --spring.datasource.url=jdbc:postgresql://customer-db:5432/customer

networks:
  customer-network:
    driver: bridge

volumes:
  customer-db:
